name: backend-ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Lint Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
